spring.datasource.url=jdbc:postgresql://localhost:5432/storyquest
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.sql.init.platform=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
upload.path=uploads/covers
avatar.upload.path=static/avatars
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
jwt.secret=storyquest-secret-key-storyquest-secret-key-123456
jwt.expiration=3600000